### ISSUE TITLE
Polymer AppLocalizeBehavior fails to load

### ISSUE THREAD

**Issue by kristfal** [webpack-contrib/polymer-webpack-loader#49]
Reproduction:

1. `bower install --save PolymerElements/app-localize-behavior`
2. Add `<link rel="import" href="../../../bower_components/app-localize-behavior/app-localize-behavior.html">` to `my-element.html` in demo

Run time error: `Uncaught TypeError: Cannot set property 'IntlMessageFormat' of undefined`

Update:

Current workaround is to exclude the script and load it outside the bundle similar to `webcomponentsjs`

**Comment by ChadKillingsworth** [comment]
This is the same as #38. I'm going to add something to the readme.

You can address this by using [WebPack shimming](https://webpack.js.org/guides/shimming/). Specifically of interest is the [exports-loader](https://webpack.js.org/guides/shimming/#exports-loader).

**Comment by ChadKillingsworth** [comment]
I took a closer look at this one. The issue wasn't the behavior directly, but the `intl-messageformat` script it includes. Needed to use the `imports-loader` so that the `this` object referred to `window`:

```js
{
  test: /intl-messageformat.min.js/,
  use: 'imports-loader?this=>window'
}
```

However, even with this there was an issue. Babel was somehow interfering. Excluding the `intl-messageformat` folder from babel got it working.
