### ISSUE TITLE
Error in Edge ( 14 )  on WIN10 when you use iron-icons

### ISSUE THREAD

**Issue by victor-perez** [webpack-contrib/polymer-webpack-loader#58]
I found a problem that only occurs in  Edge ( 14 ) for Windows 10. When I include `iron-icon`  I get the following errors:
```
SCRIPT438: Object doesn't support property or method 'call'
localhost:9000 (65,315)
SCRIPT438: Object doesn't support property or method 'byKey'
bundle.js (18185,9)
```
This problem is not in IE11, FF, CH and even not on Edge mobile.
I've used the demo code and only added `iron-icon` like this:
```
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="../bower_components/iron-icons/communication-icons.html">
<link rel="import" href="../bower_components/iron-icon/iron-icon.html">

<dom-module id="my-element">
  <template>
    <iron-icon icon="communication:business"></iron-icon>
    <h1>Hello, World! It's [[today]].</h1>
  </template>
  <script>
    // Heyyyy, we're pulling in a Node module!
    import format from 'date-fns/format';

    class MyElement extends Polymer.Element {
      static get is() { return 'my-element'; }
      static get properties() {
        return {
          today: {
            type: String,
            value: function() {
              return format(new Date(), 'MM/DD/YYYY');
            }
          }
        }
      }
    }

    window.customElements.define(MyElement.is, MyElement);
  </script>
</dom-module>
```
What I understand of this error is the loading order of `iron-meta` that gives this problem. So it looks like `polymer-webpack-loader` is breaking the required loading order what is needed for `iron-icon`

**Comment by ChadKillingsworth** [comment]
Well it definitely works in Chrome and FireFox. I'm not at a place where I can test this on Edge.

But in any case, if the loading order is broken it's because the internal dependencies in these icons are not compatible with modules. They will need to be for Polymer 3, so your best bet is to file an issue on the exact element that has a problem (which will take some digging). If you can find a way to change it so that it works with standard Polymer tooling and with webpack, then I can make sure that PR gets attention.

But I'm not sure that there is anything the loader can do about this. Scripts are not the same as modules so issues with individual elements are bound to crop up.

**Comment by Brian-McBride** [comment]
Victor, I'm wondering if you tried importing the iron-meta dependencies directly? It's a pain, but it seems that might get webpack into putting them into the right order.

**Comment by victor-perez** [comment]
@ChadKillingsworth I think you right it should be fixed inside `iron-icon`. I've looked more into this and I don't think the problem is in the loading order but more in how `iron-icon` is using `iron-meta`  on line [146](https://github.com/PolymerElements/iron-icon/blob/master/iron-icon.html#L146) you see `Polymer.Base.create('iron-meta', {type: 'iconset'})` but this is not ready when it used on line [187](https://github.com/PolymerElements/iron-icon/blob/master/iron-icon.html#L187) in Edge.

@Brian-McBride I tried and it was not solving the problem.

I've created a new issue under https://github.com/PolymerElements/iron-icon/issues/111
